# -*- coding: utf-8 -*-
# PAGE OBJECTS FILE >>> (autogenerated)


class Page(object):
    html = "html"
    username = "#user-name"
    password = "#password"
    loginButton = "#login-button"
    css_4 = "#item_1_title_link > div"
    css_5 = "#inventory_item_container > div > div > div > button"
    css_6 = "#shopping_cart_container > a > svg > path"
    checkOutButton = "#cart_contents_container > div > div.cart_footer > a.btn_action.checkout_button"
    firstName = "#first-name"
    lastName = "#last-name"
    zipCode = "#postal-code"
    css_11 = "#checkout_info_container > div > form > div.checkout_buttons > input"
    css_12 = "#checkout_summary_container > div > div.summary_info > div.cart_footer > a.btn_action.cart_button"
    css_13 = "#checkout_complete_container > h2"
